language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Cache 활성화
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - sudo apt-get install jq
  - curl -Ls -o codacy-coverage-reporter-assembly.jar $(curl -Ls https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({content_type, browser_download_url} | select(.content_type | contains("java-archive"))) | .[0].browser_download_url')
after_success:
  - export CODACY_PROJECT_TOKEN="cee8d134eaed4564adfc5b0cfa0fdc65"
  - ./gradlew jacocoTestReport
  - java -jar codacy-coverage-reporter-assembly.jar report -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
  
# clean 후 Build (Build시 자동으로 test 수행)
script: "./gradlew clean build test"
